### ISSUE TITLE
SO moves to jQuery 1.12.4 

### ISSUE THREAD

**Issue by catb0t** [soscripted/sox#108]
[We're updating jQuery to 1.12.4 tomorrow](http://meta.stackexchange.com/q/284996/310919).

The list of deprecations in this version is [here](https://api.jquery.com/category/deprecated). I don't think SOX is heavily affected from a quick scan, but we'll see, won't we. :)

**Comment by shu8** [comment]
@catb0t thanks for the notice! I never saw that meta post, so this is really useful.

However, I'm really busy atm with school stuff, so most of SOX is at a standstill right now. I'll try to get everything moving again ASAP, but might be a few weeks :(

But SOX is still alive!! :D

**Comment by catb0t** [comment]
I totally understand, don't worry about it :)

**Comment by shu8** [comment]
Actually, now that I think about it, I don't think this will affect SOX at all, because SOX requires a version of jQuery itself in the metadata block:

    // @require      https://code.jquery.com/jquery-2.1.4.min.js

so all SOX code *should* use jQuery 2.1.4. However, I know there are inconsistencies with how userscripts run between Chrome and Firefox, so I'm going to just test the script for a while (whenever I get some more time) on both Chrome and FF and check everything works.

Thanks again! :)

BTW I pushed v2.0.1 to master today, so you can install that to get most bugs fixed :)

**Comment by shu8** [comment]
@catb0t so I went through (I think) all of the features today, and they all seemed to be working as they should, so I think the jQuery update didn't affect SOX in any way! :)

Thanks again for informing us about the change!
