### ISSUE TITLE
Kbd/List feature in edit toolbar not included in Undo

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#112]
### Installed Version: 2.0.1  Environment: Firefox/Greasemonkey

---
### Expected Behavior

All edits subject to Undo arrow or Ctrl-Z.

---
### Actual Behavior

Changes made by the Kbd/List feature cannot be undone using the Undo arrow or Ctrl-Z.

---
### SOX Errors logged to the browser console (if available)

Didn't bother with console output because this seems more like a design issue than a bug.

**Comment by shu8** [comment]
@fixer1234 This might not actually be possible, because SE use their own undo method... but I'll see if I can look into their source code and use it for SOX... no promises it'll work though :/

**Comment by shu8** [comment]
I've looked around, and I honestly don't even know where to start on this one, so I'm going to add the help-wanted tag, and hope for the best! :)

**Comment by IStoleThePies** [comment]
What exactly is the problem here?

**Comment by fixer1234** [comment]
@IStoleThePies This is a feature request for the SOX editor feature that inserts <kbd> markdown and bullets (the "Add KBD and list buttons to editor toolbar" feature).  The action of these buttons can't be undone using the undo arrow in the toolbar or ctrl-Z.

**Comment by Franck-Dernoncourt** [comment]
> SE use their own undo method

Do you think it could be possible to disable SE's own undo method (so that the browser's default undo method is used)? If so, that could be an interesting feature, as SE's undo method can be annoying.

**Comment by shu8** [comment]
@Franck-Dernoncourt that's an interesting idea, but I've had a look [at their code](https://cdn-dev.sstatic.net/Js/wmd.en.js), and if it *is* possible, I have no idea how to :(

I don't think it'll be possible to do that unfortunately 😞

**Comment by Franck-Dernoncourt** [comment]
I have submitted a feature request to Stack Exchange meta: [An option to disable the editor's undo/redo feature](http://meta.stackexchange.com/q/289087/178179). The editor is a `textarea`:

![image](https://cloud.githubusercontent.com/assets/15331/21578655/c65f8708-cf56-11e6-9c57-84aceea1e1c6.png)

and [any decent browser  has undo/redo (ctrl-z, ctrl-y) for text areas built in already](http://stackoverflow.com/q/5221755/395857).

**Comment by shu8** [comment]
Upvoted :)

**Comment by Franck-Dernoncourt** [comment]
Some ideas: [Is there a way to disable the hotkeys?](
http://meta.stackexchange.com/q/2980/178179)

**Comment by shu8** [comment]
@Franck-Dernoncourt wow I'd tried doing something similar to what Rob did in his answer there, but the  reason is wasn't working for me was that I WASN'T DOING IT ON THE PARENT!!! 😠 

In [dev z](https://github.com/soscripted/sox/raw/dev/sox.user.js), I've now made it so that if you press ctrl + Z or Y, then it rejects the SE's handler and lets the browser take care of it. as a result, you can undo things the kbd and list buttons do.

Note: to undo the KBD tags, you need to press ctrl+z **three** times, simply because there are 3 steps I take in doing it, so you need to undo 3 times :(

sorry, but I doubt there's anything I'll be able to do about that.

@fixer1234 please could you also confirm this works for you? :)

**Comment by fixer1234** [comment]
@shu8 Running Dev Z.  The undo arrow now works, and clears the Kbd markup in one click.  Ctrl-Z highlights the entire line the first time, then the second Ctrl-Z removes all of the Kbd markup in one step, and only that.  So it appears to be working (and better than you think it's working, unless this is a rare instance where Firefox actually works better).  I'll leave this for you to close when you're done with it and satisfied that it works for everybody.

**Comment by shu8** [comment]
@fixer1234 lol it might be one of those rare instances 😆 

@Franck-Dernoncourt please could you check how many times you need to undo? I'm just curious... :)

**Comment by Franck-Dernoncourt** [comment]
I need to undo three times :-)

One issue I have noticed is that some actions cannot be undone. E.g. adding a list (using the list icon) cannot be undone with  <kbd>Ctrl</kbd> +  <kbd>z</kbd>.

**Comment by shu8** [comment]
@Franck-Dernoncourt ah... yeah that's happening to me as well -- that must be the reason why SE originally had their own undo handler.

I see 2 options right now;

- use SOX's list button -- it lets you just write your list on separate lines, then you can just select the lines and click the button and it will listify it for you
- use SE's undo *button* rather than Ctrl+Z ing

Because, I can't fix this without breaking the kbd undo feature 😞 

@fixer1234 yep, it's a rare FF good thing 😝
