### ISSUE TITLE
Allow replying to own chat messages

### ISSUE THREAD

**Issue by somebody1234** [soscripted/sox#118]
Should be pretty self-explanatory.

**Comment by shu8** [comment]
@somebody1234 Not really... not sure if I'm just being stupid here... please could you expand? :)

**Comment by somebody1234** [comment]
There isn't a reply button on your own messages, sometimes I reply to clarify one of my own messages or answer a question I asked in a previous message, I'd think this would be really helpful for me.

**Comment by shu8** [comment]
hmm I'd have to look into how replies work, but sounds doable.

I'd expect a timeframe between v2.0.2 and v2.0.5 atm...

**Comment by shu8** [comment]
@somebody1234 done in [latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by IStoleThePies** [comment]
@shu8 Small issue, the reply button has a grey bar around the icon:

<img width="975" alt="screen shot 2016-11-03 at 7 55 50 pm" src="https://cloud.githubusercontent.com/assets/5375326/19989854/bc566da0-a1ff-11e6-92b5-e17b55b64e95.png">

**Comment by shu8** [comment]
@somebody1234 thanks! I'll get that fixed

**Comment by somebody1234** [comment]
@shu8 That wasn't me

**Comment by shu8** [comment]
@somebody1234 whoops! sorry! I meant @IStoleThePies :/

either way, this is fixed in [dev version o now](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by IStoleThePies** [comment]
@shu8 Just noting, when you hover over other posts a small white box surrounding the options covers the timestamp:

<img width="124" alt="screen shot 2016-11-05 at 1 38 45 pm" src="https://cloud.githubusercontent.com/assets/5375326/20032295/ee262046-a35d-11e6-9c94-9c644495bb98.png">

However when you hover over your own:

<img width="95" alt="screen shot 2016-11-05 at 1 38 01 pm" src="https://cloud.githubusercontent.com/assets/5375326/20032296/f951d212-a35d-11e6-9c59-90adc84e2bb3.png">

Perhaps you could add a small white box behind the reply icon on your own posts?

**Comment by IStoleThePies** [comment]
@shu8 Also, could you disable notifications on self-replies? I see a desktop notification pop up every time I reply to myself.

**Comment by shu8** [comment]
@IStoleThePies Could you post that a new issue please? 

It's would actually be a new feature, which we'd need to look into how to do! :)

**Comment by IStoleThePies** [comment]
@shu8 Both of those bugs I mentioned or just the second?

**Comment by shu8** [comment]
Just the notification one. I've fixed the other one locally.. just need to
push it in a bit

**Comment by IStoleThePies** [comment]
@shu8 Seems to be working now (sort of). By the way, I rewrote the reply button function to fix a lot of bugs:

    replyToOwnChatMessages: function() {
            //I use $(document).on instead of .each, since using .each wouldn't apply to messages loaded via "Load more messages" and "Load to my last message"

            $(document).on('mouseenter', '.mine .message', function() {
                //Remove excess spacing to the left of the button (by emptying .meta, which has "&nbsp" in it), and set the button color to the background color
                $(this).find('.meta').empty().css({"background-color": $(this).parent().css("background-color"), "padding-right": "1px"}).show().append(replySpan);
                //The "padding-right: 1px" is to avoid some weird bug I can't figure out how to fix
            }).on('mouseleave', '.mine .message', function() {
                $(this).find('.meta').hide().find('.newreply').remove();
            })

            //Do the same thing if you hover over the timestamp
            .on('mouseenter', '.mine .timestamp', function() {
                $(this).next().find('.meta').empty().css({"background-color": $(this).parent().css("background-color"), "padding-right": "1px"}).show().append(replySpan);
            }).on('mouseleave', '.mine .timestamp', function() {
                $(this).next().find('.meta').hide().find('.newreply').remove();
            })

            .on('click', '.newreply.added-by-sox', function(e) {
                var $message = $(e.target).closest('.message'),
                    id = $message.attr('id').split('-')[1],
                    rest = $('#input').focus().val().replace(/^:([0-9]+)\s+/, '');
                $('#input').val(':' + id + ' ' + rest).focus();
            });

            var replySpan = $('<span/>', {
                class: 'newreply added-by-sox',
                'title': 'link my next chat message as a reply to this'
            });
        },

This fixes the following bugs I found:

- The star count on my own messages didn't show next to the message (".stars" applies to both the message's meta icon and the stars next to the message. I decided to empty the meta altogether instead of hiding the buttons, which fixed this problem as well as another one)
- The background color of the reply button didn't match the color of the message (my code sets the button's color to that of its parent, which is the message)
- The reply button doesn't show up on older posts if you click "Load more messages" and "Load to my last message" (I chose to forgo .each in favor of adding the reply button whenever you hover over your own message)
- There's an excess left spacing on the reply button (caused by "&nbsp" in the meta. Emptying the meta resolved this)
- Moving your mouse over the reply button from right to left on the timestamp makes it flicker (seems like a manifestation of the problem I mentioned before. After messing around, the only fix I found was to add a right padding to the button, which shifts it a bit but removes the problem):

![untitled-2](https://cloud.githubusercontent.com/assets/5375326/20694268/fe4723ce-b5b1-11e6-9939-e6f59e5dec82.gif)

Tell me if you think it's all right or you need any clarification :)

**Comment by shu8** [comment]
@IStoleThePies Thanks! :D I've cleaned up the other issue and changed the URL in the comment in the code locally, which will be there in dev ae :)

**Comment by IStoleThePies** [comment]
@shu8 Sounds good!

By the way, should we include a reply link on the message dialog boxes (when you click on the arrow at the left of the message)? That would let people reply to themselves from a permalink.

**Comment by shu8** [comment]
@IStoleThePies It's definitely doable, but I doubt I'll have any time this weekend :(

I'll look into it next week, but please feel free to submit a pull request if you want to! :)

**Comment by IStoleThePies** [comment]
@shu8 I'm busy this weekend too. I'll see what I can do :/

**Comment by shu8** [comment]
Lol no problem! :)
