### ISSUE TITLE
Header problems

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#152]
### Installed Version: 2.0.2DEVac  Environment: Tampermonkey 

---

The header seems to disappear on Ask Patents, Aviation, Biology, Chemistry (the equations at the top of the header disappear), Cryptography, Drupal Answers (the subtle light rays in the header disappear), ExpressionEngine, Information Security, Magento, Mi Yodeya, Movies and TV, Music Practice & Theory, Network Engineering, Personal Finance & Money, Raspberry Pi, Salesforce (not actually the header, but a background image), Signal Processing, Skeptics, Software Engineering (header gets a bit distorted), Software Recommendations, and Travel.

On some of those sites, the header is really just dropping to around the bottom of the page.

It also shortens on Android Enthusiasts, Meta Stack Exchange (a teeny bit), and Wordpress. It also becomes larger on Ask Ubuntu (this is due to the fixed header and would be trickier to fix).

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-betterCSS","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-grayOutVotes","Appearance-hideHireMe","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Appearance-disableOwnPostVoteButtons","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Flags-flagOutcomeTime","Flags-flagPercentages","Unsorted-downvotedPostsEditAlert","Unsorted-parseCrossSiteLinks","Unsorted-replyToOwnChatMessages"]

**Comment by enki-code** [comment]
The topbar is disappearing?  If so, the problem is that StackExchange doesn't use a consistent design and trying to code for each possible proving to be quite troublesome.

**Comment by IStoleThePies** [comment]
@enki-code By header, I meant the area behind the site logo.

**Comment by shu8** [comment]
The issue is basically that we can't apply a single CSS rule to every site because SE's made each site design subtly different. 

We don't think we'll be able to find a way to globally apply the fixed topbar whilst still keeping the design perfect on all sites without manually testing each site and then adding an exception in the code for each site. 

We'll try looking into certain sites when we get some more time on our hands but it looks like it's going to have to stay like this for a bit more time:(

**Comment by shu8** [comment]
@IStoleThePies ok, so I just had a bit of time and went through your list.

I've applied the 'patch' we made for Software Recs and Raspberry Pi to:

- aviation
- biology
- chemistry
- crypto
- drupal
- expressionengine
- security
- magento
- judaism
- movies
- music
- networkengineering
- money
- dsp
- skeptics
- travel

which fixes most of the bug on those sites. You can get it in [dev ae](https://github.com/soscripted/sox/raw/dev/sox.user.js).

However you'll still notice some movement after page load on most of those sites: this is what would take a lot of time, because it needs someone to go through each and every site and experiment with the sites to see which CSS tweak fixes it, which is just too time-consuming for not too much gain :(

I'm afraid it's going to have to stay like this for at least the near-future :/ (this feature is starting to be an absolute pain :P)

**Comment by IStoleThePies** [comment]
@shu8 @enki-code I think I might have come up with a solution:

    fixedTopbar: function() {
            // Description: For making the topbar fixed (always stay at top of screen)
            //When you're logged out on Area 51, some annoying notification screws up the topbar. Can't figure out how to fix it, so I just disabled it when you're logged out.
            if (sox.location.on('askubuntu.com') || (!sox.user.loggedIn && sox.location.on('area51.stackexchange.com'))) {
            }
            else{
                $("body").css({
                    'padding-top': parseInt($('body').css('padding-top')) + 34 + 'px'
                });

                $('.topbar').css({
                    'position': 'fixed',
                    'z-index': '900',
                    'margin-top': '-34px'
                });
            }
        },

I rewrote it with the premise of moving everything besides the topbar down. I haven't tested it on every site, but so far I only found a problem on Ask Ubuntu (in which the topbar acts differently from other sites) and Area 51 (when logged out, a popup will appear at the top and screw everything up). I spent a good 2.5 hours trying to fix the Area 51 problem but in the end just gave up, so I disabled it on both of those sites.

**Comment by shu8** [comment]
@IStoleThePies thanks for that! :) 

I'll try your code on the weekend and test it :)

It's annoying how simple the solution might be now :P

**Comment by IStoleThePies** [comment]
@shu8 I've fixed a few bugs, including the Area 51 one and another one where the body would lose its padding if you closed or dragged a bounty/flag/etc. popup:

        fixedTopbar: function() {
            // Description: For making the topbar fixed (always stay at top of screen)

            //For some reason, chats don't need any modification to the body
            if (sox.site.type == 'chat') {
                $('.topbar').css({
                    'position': 'fixed',
                    'z-index': '900'
                });
            }

            //Disable on Ask Ubuntu
            else if (!sox.location.on('askubuntu.com')) {
                $('body').css({
                    'padding-top': $('#notify-table').height() + $('.topbar').height() + 'px' //If the Area 51 popup closes or doesn't exist, $('#notify-table').height() = 0
                });

                $('.topbar').css({
                    'position': 'fixed',
                    'z-index': '900',
                    'margin-top': '-34px'
                });

                //Area 51 popup:
                $('#notify-table').css({
                    'position': 'fixed',
                    'z-index': '900',
                    'margin-top': '-65px'
                });

                var checkShift = new MutationObserver(function() {
                    $('body').css({
                        'padding-top': $('#notify-table').height() + $('.topbar').height() + 'px'
                    });

                    $('.topbar').css({
                        'position': 'fixed',
                        'z-index': '900',
                        'margin-top': '-34px'
                    });
                })

                checkShift.observe(document.body, { attributes: true }); //Re-add padding if you drag/close a popup box

                checkShift.observe(document.getElementById('notify--1'), { attributes: true }); //Move body and topbar up if you close the Area 51 popup
            }
        },

This should work fine. Bear in mind, I've never used MutationObserver before, so this might not be the cleanest way to fix those problems I mentioned (I'm not really sure).

**Comment by shu8** [comment]
@IStoleThePies It seems to be pretty perfect! :D 

Thank you sooooooo much for fixing it -- it's a much more clever way of going around the entire problem compared to what we could come up with!

[Added your code in dev af](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

**Comment by IStoleThePies** [comment]
@shu8 Small bug — the modified code now sets the body's padding to 3134 on Area 51 (if you're logged out), instead of doing 31 + 34 = 65px. The result is a huge spacing on the site. :)

**Comment by shu8** [comment]
@IStoleThePies sorry, I got rid of those mutationobservers because something was causing it to crash in FF. I've re-added it now, so it should be fixed [in dev am](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

You might need to delete Area51 cookies if the banner doesn't show anymore! :)
