### ISSUE TITLE
Which features do YOU use?

### ISSUE THREAD

**Issue by shu8** [soscripted/sox#166]
@enki-code and I are trying to find out which features people find the most useful, but more importantly, **which features do you not like?**

Are there any features in SOX that you think...:

- are not useful at all?
- could be better?
- don't work as they should?

Or do you have any ideas for new features?

Also, we have [a Gitter chat room](https://gitter.im/soscripted/sox?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) that anyone can access if they have a Github account! Feel free to drop in if you ever have a question! :)

We'd like to remove features that it seems nobody is using to help make our features more manageable, but we're more than open to adding new ones! :)

**Comment by fixer1234** [comment]
@shu8 I generally post any issues and improvement suggestions.  The "not useful at all" really depends on the user.  Some features only work on selected sites.  If you don't use those sites, those features won't be useful.  Some are focused on things like bounties.  Those will be useful for people who focus on bounties, and irrelevant to those who don't.  Features about appearance preferences will depend on user preferences.  You just got involved with a question about how to hide the HNQ module.  Some people love some or all of the sidebar modules and some hate them.

If you're looking for general input on usage, create a form that lists the features and has an input  or selection box next to each.  Input choices could be: Especially valuable to me, Handy, Implementation inadequate for my purposes, Irrelevant to me, Counter-productive/Don't like it.

Useful user information to collect for context: Favorite sites, Occasional sites, Frequent SE visitor/Occasional visitor, Reviewer regularly/occasionally/rarely, Editor regularly/occasionally/rarely, Chat regularly/occasionally/rarely, Q&A post regularly/occasionally/rarely, Comment regularly/occasionally/rarely.

**Comment by shu8** [comment]
@fixer1234 thanks! I like that idea and I'll start making a form now and post it ASAP :)

**Comment by IStoleThePies** [comment]
Here's a list of features I don't have enabled, either for personal aesthetic reasons or because I don't like the idea:

- Color answerer's comments (I personally think the highlighted username looks fine as it is)
- Add display name before gravatar in topbar (I just don't see any point to this feature)
- Add Scroll To Top button (I understand the purpose and it may be useful to some people, but it's not very useful to those who know how to scroll to top using keyboard commands)
- Add a button to the editor toolbar to start side-by-side editing (messes with page layouts and doesn't seem to be that needed)
- Warn you when you are not logged in (this is already done if someone tries to upvote, downvote, etc. It's not really necessary to warn someone until they actively try to perform a certain action)
- Change 'share' link to format of [post-name](url) (personally never needed it. I mostly use the share link to send answers to my friends, but if I need to write it in the [post-name](url) format, I can do it myself)
- Prepend 'Chat - ' to chat tabs' titles (seems unnecessary imo)

Here's the ones where I don't understand what they do:

- Display reviewer stats on /review/suggested-edits in table form
- Improve answer visibility by listing top answers
- Change highlighting for questions with favorite tags
- Replace triangular bullets with normal ones (no idea where these bullets are. It doesn't seem to refer to ones in a question or answer)
- Display linked posts inline by clicking on an arrow
- Pre-defined edit comment options (checkboxes)
- Add KBD and list buttons to editor toolbar
- Filter the hot network questions by their attributes
- Add buttons to user profiles to change user write access directly from a chat room
- Align badges by their class on user profile pages

On a side note, I really like the idea for "Add a label on questions which are hot-network questions", but I'd prefer if it were a bit more aesthetic on hot-network questions ("HOT" can be kind of hard to see since it's so far to the right) and if it distinguished hot-network questions on a list of questions.

**Comment by fixer1234** [comment]
@IStoleThePies descriptions for ones in the "don't understand what they do" category:

-  Display reviewer stats: [Unnecessary “and”s in reviewer stats](http://meta.stackexchange.com/a/277474/269940)  For some reason, I can never find where to display this.

- Improve answer visibility by listing top answers: no canned description on the wiki page.  I tried it once and found it counter-productive because I don't always agree with the voting.  Might be handy if you're looking for a quick answer to a common question and need to skim through a bunch of threads.  I forget whether it hides low vote answers, or moves the top-rated answers to the top, or what.

- Change highlighting for questions with favorite tags:  [Should favorite tag highlighting in question lists be changed?](http://meta.stackexchange.com/q/238591/269940) (I haven't picked favorite tags, so I don't use it.)

- Replace triangular bullets: [Can we get rid of the disclosure triangles that don't disclose anything on the edit screen?](http://meta.stackexchange.com/q/195779/269940)  (I also haven't found a need for this one)

- Display linked posts inline by clicking on an arrow: This can be handy.  An arrowhead is added to the links.  Clicking that displays the linked post in place.

- Pre-defined edit comment options (checkboxes): adds checkboxes to insert canned, two-word descriptions into the edit comments box for common types of edits:

![sox edit comments](https://cloud.githubusercontent.com/assets/10065766/21513380/9ecc0956-cc85-11e6-9aaf-8e2be350a574.png)

- Add KBD and list buttons to editor toolbar: [Key equivalent for <kbd></kbd>](http://meta.stackexchange.com/q/102841/269940)  Adds two buttons; one inserts the keycap markup (which is handy), the other inserts the hyphen placeholder and spacing for a bullet, but doesn't handle line spacing (so limited value).

- Filter the hot network questions by their attributes: Lets you specify filters for HNQ posts based on site, title, or words in title:

![sox hnq filter](https://cloud.githubusercontent.com/assets/10065766/21513477/13bd87f2-cc87-11e6-8d07-ab6e3f957640.png)

- Add buttons to user profiles to change user write access directly from a chat room:  [Simplify chat UI for granting write access](http://meta.stackexchange.com/a/276846/269940)

- Align badges by their class on user profile pages: [Align badges by class](http://meta.stackexchange.com/a/277656/269940)

**Comment by shu8** [comment]
thanks @IStoleThePies and @fixer1234, I'll look into those features :)

@fixer1234:

- for your first bullet, you can find this on a suggested edit such as [this one](http://meta.stackexchange.com/review/suggested-edits/48421) and clicking `more` just under the reviewer info:

![this](https://cloud.githubusercontent.com/assets/8850830/21527748/326ea0e8-cd25-11e6-8496-24e848c68bc8.png)

- about the predefined edit checkboxes -- I realise you may not know that you *can* add your own canned responses! The feature adds a menu option under the HELP menu:

![this](https://cloud.githubusercontent.com/assets/8850830/21527768/69845aaa-cd25-11e6-9146-48954dad34c8.png)

I realise now that I never said that anywhere, so I'll be adding that to the hover-info on the feature

---

@IStoleThePies I get where you're coming from about the design of the HOT sign, but I'm appalling at anything UI-related -- do you have any thoughts on what it could look like instead? :)

**Comment by IStoleThePies** [comment]
@shu8 I think something as simple as [this](https://stackapps.com/questions/3535/stack-exchange-favorite-users?rq=1) would work. What do you think?

**Comment by shu8** [comment]
@fixer1234 hmm yeah I could make a thick red left border, but you said it was easy to miss, so what about just moving it to the left of the title?

![this](https://cloud.githubusercontent.com/assets/8850830/21529918/d5ed12b8-cd34-11e6-9d5d-47ffd5fb1a62.png)

I could adjust the height and stuff to make it fit in a bit more...?

**Comment by IStoleThePies** [comment]
@shu8 Hmm...I think that would work, but perhaps you could have a flame symbol instead of the word "HOT"? Kind of like this:

<img width="1440" alt="screen shot 2016-12-28 at 1 51 46 pm copy" src="https://cloud.githubusercontent.com/assets/5375326/21530211/1bbef5fe-cd0d-11e6-8399-f8d762778385.png">

This is a pretty crude image, but what do you think of the idea?

**Comment by shu8** [comment]
I like it! I'll get that done! :)

**Comment by fixer1234** [comment]
I was just about to post that the vertical bar idea sucks, but I see the flames icon idea.  Brilliant!

**Comment by shu8** [comment]
@fixer1234 @IStoleThePies can you guys see this: 🔥 ?

**Comment by IStoleThePies** [comment]
@shu8 I see this:

<img width="686" alt="screen shot 2016-12-28 at 3 32 22 pm" src="https://cloud.githubusercontent.com/assets/5375326/21531023/deb46b7a-cd12-11e6-8a0e-647fac763320.png">

**Comment by shu8** [comment]
@fixer1234 @IStoleThePies ok... I've just pushed [dev v](https://github.com/soscripted/sox/raw/dev/sox.user.js) with the 🔥 icon.

Can you see what it looks like when it's next to a title, eg http://stackoverflow.com/questions/41364383/ atm and tell me if it looks bad? :)

**Comment by fixer1234** [comment]
@shu8 I can see it in the browser but not in the email I got about the post.  I would have no idea that it represented a fire.  On github, it looks like this, only what I guess are sparks are too small to see, so it's a yellow animal footprint.

![sox icon](https://cloud.githubusercontent.com/assets/10065766/21531281/af242204-cd14-11e6-9955-547faa1a6692.png)

Your "I see this" snap reminds me of a hamburger joint from years ago, called Bob's Big Boy.  They had a statue in front of a fat kid with big pointed hair.  I wouldn't associate that with fire.

Your "otherwise" icon looks like a dreamy wiff of vapor from a hot coffee or soup.

IStoleThePies's icon is clearly a raging fire.

OK, just loaded Dev V and it's a moot point.  This is what appears:

![sox icon1](https://cloud.githubusercontent.com/assets/10065766/21531500/8effb61c-cd16-11e6-87c8-fa07dd0b9fab.png)

**Comment by fixer1234** [comment]
BTW, I had no issue with the original "HOT", or sticking that to the left of the title if the concern is that it isn't noticeable off to the right.

**Comment by IStoleThePies** [comment]
@fixer1234 Seemed to work for me. 😕

**Comment by IStoleThePies** [comment]
@shu8 Uh, so I came back here and the fire image I see is different yet again:

<img width="654" alt="screen shot 2016-12-29 at 11 48 32 pm" src="https://cloud.githubusercontent.com/assets/5375326/21559814/62e40d56-ce21-11e6-9ede-ac9ea653cbae.png">

Though, this actually looks really good on the question, in my opinion:

<img width="746" alt="screen shot 2016-12-29 at 11 49 28 pm" src="https://cloud.githubusercontent.com/assets/5375326/21559820/791aca06-ce21-11e6-8526-db707204bdf7.png">

**Comment by fixer1234** [comment]
@shu8 @IStoleThePies On my system it renders with what I guess is a unicode placeholder:

![sox icon2](https://cloud.githubusercontent.com/assets/10065766/21561739/b3d6482e-ce3e-11e6-9d83-662592bb714e.png)

**Comment by IStoleThePies** [comment]
@fixer1234 I think it depends on your OS.

**Comment by shu8** [comment]
@fixer1234 @IStoleThePies yeah it must depend on which fonts you have installed.

I guess that's not going to work then. I'll see if I can find a better image somewhere :)

**Comment by shu8** [comment]
@IStoleThePies would it be possible for you screenshot just that image on your Mac and post it here?

I could save it in this repo then and use it as a resource, which will cache it so it isn't requested for every single hot question

**Comment by IStoleThePies** [comment]
@shu8 Er, I'm not entirely sure if those images are copyrighted and if that'd be a problem. So I wouldn't know if that's viable 😕

**Comment by shu8** [comment]
@IStoleThePies hmm didn't think of that :/

No worries, I'll find something :)

**Comment by Franck-Dernoncourt** [comment]
My top 5 favorite features:

1. Add a button to the editor toolbar to start side-by-side editing
2. Change 'share' link to `(question title)[URL]`
3. Add KBD and list buttons to editor toolbar
4. Hide the Community Bulletin module
5. Hide the Hot Network Questions module

It saves me plenty of time. I used to have a voice command for 2 and 3 (KBD). 1 makes editing so much more convenient.

**Comment by fixer1234** [comment]
Appearance
    Add a label on questions which are hot-network questions: Handy
    Add a link to the bottom of a post to reveal all spoilers in a post: Irrelevant
    Add a mod diamond to the topbar to alert you of new questions on the site's child-meta: Very useful
    Add display name before gravatar in topbar: Dislike
    Add highlighted tags to closed/on hold/duplicate/migrated questions on question lists: Useful
    Add Scroll To Top button: potentially handy but have never actually used it
    Add the author's name to notifications in the inbox: High value feature
    Add the SO logo after employee names to make them stand out: Useful
    Align badges by their class on user profile pages: nicer presentation but low priority
    Change highlighting for questions with favorite tags: Irrelevant
    Color answerer's comments: Useful
    Differentiate spoilers from empty blockquotes: Irrelevant
    Display reviewer stats on /review/suggested-edits in table form: makes the info more usable but infrequently access it
    Fix topbar position: Useful
    Improve answer visibility by listing top answers: Counter-productive
    Make bounty box draggable: Irrelevant
    Replace triangular bullets with normal ones: Irrelevant
    Show meta and chat buttons on hover of a site under the StackExchange button: Useful
    Show tags for the question an answer belongs to on search pages (for better context): Very Useful

Comments
    Add a confirmation dialog when navigating away on pages whilst still typing a comment: High value feature
    Add a darker border underneath comments if there are some hidden after it: Useful
    Add reply links to comments for quick replying (without having to type someone's username): Very useful
    Copy 'show x more comments' link to the top: Irrelevant
    Move the 'start a bounty' link to before the comments: Irrelevant
    Show your comment and comment replies scores in your profile tabs: Handy
    Use Ctrl+I,B,K (to italicise, bolden and add code backticks) in comments: Potentially handy but infrequently used
    View linked images (to imgur) in comments inline: Useful

Editing
    Add a button to the editor toolbar to start side-by-side editing: High value feature
    Add a notification to your inbox when a question you downvote is edited: High Value feature
    Add a tooltip to posts showing the last revision's comment on the word 'edited' in 'edited [date] at [time]': Very useful
    Add KBD and list buttons to editor toolbar: KBD is useful, List useless since better  implementation already built into editor
    Add more features to the markdown editor: Find/Replace is useful, Autocorrect too limited to be useful
    Inline editor regardless of reputation: Useful
    Make title edits show seperately rather than merged in edit suggestions: Useful, but would be much more useful with a toggle since sometimes it helps and sometimes it hinders
    Pre-defined edit comment options (checkboxes): Handy

Flags
    Show flagging percentages for each type in the Flag Summary: Nicer presentation but low priority
    Show the flag outcome time when viewing your Flag History: Useful
    Show the total percentage of helpful flags as a coloured bar on the Flag Summary Page: Nicer presentation but low priority

Sidebar
    Add an arrow to linked posts in the sidebar to show whether they are linked to or linked from: Potentially handy but infrequently used
    Filter the hot network questions by their attributes: Irrelevant
    Hide the Community Bulletin module: Counter-productives
    Hide the Hot Network Questions module: Counter-productives
    Hide the Looking for a Job module: Handy

Chat
    Add buttons to user profiles to change user write access directly from a chat room: Potentially handy but not used yet
    Add reply signs to your own chat messages: Potentially handy but not used yet
    Prepend 'Chat - ' to chat tabs' titles: Useful

Voting
    Add extra CSS for voting signs and favourite button (currently only on Android SE): Irrelevant
    Disable vote buttons on your own posts: Handy
    Gray out deleted vote buttons: Handy
    Make vote buttons next to posts sticky whilst scrolling on that post: Irrelevant

Unsorted
    Add an option to filter bounties by their amount: Irrelevant
    Always show the 'Link from the web' box when uploading an image: Useful
    Change 'share' link to format of post-name: Useful
    Display linked posts inline by clicking on an arrow: Useful
    Hide on hold, closed, or duplicate questions or deleted answers: Counter-productive
    Parse titles to links cross-SE-sites: Useful
    Show when the post's author was last seen and whether they are registered in the comments section: Very Useful
    Warn you when you are not logged in: Very Useful

**Comment by shu8** [comment]
@Franck-Dernoncourt I'm glad they're of so much use to you! 😃 

@fixer1234 you're toggle idea for the title edit diff sounds interesting. I could put a little toggle sign (http://fontawesome.io/icon/toggle-on/) next to the title to let you turn it off? does that sound any good? and where would you place it? I'm thinking just after the title, but that will never be in the same place then because each title has a different length :/

---

I think I've had 3 or 4 people saying they think the `Replace triangular bullets with normal ones` feature is useless now, so that's going away. it's only a very minor UI tweak which I think you'd probably not notice so there's no point having it anymore.

**Comment by fixer1234** [comment]
@shu8 Nice.  I guess the logical location would be to the left of the title (or as a prefix to the title on that line), or above the title?

**Comment by shu8** [comment]
@fixer1234 done in [dev ac](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

![this](https://cloud.githubusercontent.com/assets/8850830/21594317/328b5f74-d119-11e6-81df-b21e798fd8ba.gif)

**Comment by fixer1234** [comment]
@shu8 Very nice!

**Comment by wgrundlingh** [comment]
In terms of the hot question "flame". It *is* OS-dependent. I'd go with something provided by FontAwesome (to remove the OS dependency), like this:
  http://fontawesome.io/icon/free-code-camp/
If you can add colour, then great. You can add a tooltip with more information if needed.

**Comment by fixer1234** [comment]
@wgrundlingh That's not bad.

**Comment by shu8** [comment]
@wgrundlingh that's an awesome idea!! I never thought about looking at logos!! 

I'll use that, make it red/orange and put in a tooltip :)

**Comment by shu8** [comment]
@fixer1234 @IStoleThePies @wgrundlingh ok.. I could make it look like this...:

![this](https://cloud.githubusercontent.com/assets/8850830/21611861/9cd24822-d1c6-11e6-8ba6-2b23856d023e.png)

but do you think it might be confusing for some people because it is the free code camp logo... :/

**Comment by fixer1234** [comment]
@shu8 1) I wasn't even familiar with that organization, so it wouldn't be confusing for me.  Well, now that you introduced the organization, I might be.  :-)    2) People will see it only if they select the feature, so its not like they will be clueless about why that symbol is sitting there.  3) Lots of symbols are kind of universal, and get used in slightly different ways by different applications.  4) Nobody owns the concept of fire, so screw 'em.  And if anyone notices and raises the issue, just say we're helping to promote that worthy cause; that's our story and we're sticking to it.

**Comment by shu8** [comment]
@fixer1234 lol, fair enough. done in [dev af](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 Nicely done!

**Comment by IStoleThePies** [comment]
@shu8 Could we also have the icon show up for hot network questions on the questions list?

**Comment by enki-code** [comment]
I'm closing this as it's starting to turn into an extended discussion / feature request.  

We appreciate all the feedback! If you have any suggestions on things we could do better please post individual issues as it will be easier to track!  Thanks again!

**Comment by shu8** [comment]
@IStoleThePies a bit late, but the HNQ sign shows up on question lists now [in dev 2.0.13](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
