### ISSUE TITLE
Have arrows show up on the linked posts page

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#172]
### Installed Version: 2.0.2DEVaz  Environment: Tampermonkey

Right now, arrows only show up for linked posts on the sidebar. On questions like [this](https://stackoverflow.com/questions/156503/how-do-you-assert-that-a-certain-exception-is-thrown-in-junit-4-tests?rq=1), there is a "see more linked questions…" link under the "Linked" section, which will list all the linked questions. Perhaps you could add arrows in those kind of pages as well?

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Editing-titleEditDiff","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Voting-betterCSS","Unsorted-alwaysShowImageUploadLinkBox"]

**Comment by shu8** [comment]
@IStoleThePies The thing is, that this feature ATM just scrapes each page on the linked section to see whether they link to the current page -- if I do this for more than about 10 or so, then SE's going to throttle you because 'you' (the script actually) are sending too many requests too quickly.

---

However I just thought that I *could* instead use the API and then it would all be done in one request... I'm not sure why I didn't do this before, unless there was a problem I've forgotten about so I'll see if I can do it, but no promises atm! :/

**Comment by shu8** [comment]
@IStoleThePies I remember now, as I start to do it -- if I use the API, it's takes a lot more requests to get each answer's id of a question and then get their body afterwards.

I think it's better to scrape the page because it's quicker (and easier :P) and seems to actually make less requests :/

**Comment by shu8** [comment]
sorry @IStoleThePies, I don't think I'll be able to get this feature request done 😞
