### ISSUE TITLE
Add numerical notifier for "notify on edit"

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#176]
### Installed Version: 2.0.3DEVb  Environment: Tampermonkey

Currently, updates to your "notify on edit" button will look like this:

<img width="560" alt="screen shot 2016-12-22 at 9 14 59 am" src="https://cloud.githubusercontent.com/assets/5375326/21428292/3fae39ce-c827-11e6-91f9-7980ecbdf766.png">

Perhaps instead, you could add a number showing how many updates there are, just like in the inbox?

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-showCommentScores","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-quickAuthorInfo"]

**Comment by fixer1234** [comment]
@IStoleThePies I noticed on a couple of your posts you include that Features Enabled list.  How do you generate that?

@shu8 I see the bold, blue message box icon in the screenshot above.  Just FYI, that doesn't appear on mine.  I have 2.0.3 Dev A loaded, so don't know if that changed in Dev B or the issue is specific to my configuration.

**Comment by shu8** [comment]
@fixer1234 the features enabled list should come be added automatically, but it seems like it's another FF-only issue *sigh* :P I'm working on a fix

it's weird you don't see the blue bold icon... It should be there since around 2.0.2devaz...

**Comment by shu8** [comment]
@fixer1234 I've fixed the auto-populate issue in [dev d](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

I need to look a bit more into your icon issue though

**Comment by fixer1234** [comment]
@shu8 Confirmed.  Auto-populate works.

**Comment by shu8** [comment]
@IStoleThePies I've added a first version of this in [dev i](https://github.com/soscripted/sox/raw/dev/sox.user.js):

![this](https://cloud.githubusercontent.com/assets/8850830/21462236/8a978ed8-c951-11e6-89f6-a1e0596a0a74.png)

As you can see, it's fairly bad-looking right now, and I'm going to change that and I'm completely open to suggestions on how the indicator could look. I couldn't manage to clone the element from the inbox onto this feature because *something* or the other kept on going wrong, and I got tired so did it myself :/

---

@fixer1234 Could you also please try installing this version on the machine with the working access token and see if it's working for you now? :)

**Comment by fixer1234** [comment]
@shu8 It appeared but the behavior is buggy (part of a collection of buggy behavior on issue #98).  It will be easier to include this there.
