### ISSUE TITLE
Feature Request: Make the AskUbuntu Topbar like every other site 

### ISSUE THREAD

**Issue by KazWolfe** [soscripted/sox#185]
### Current Behaviour

Currently, the AskUbuntu Topbar looks very dissimilar to the topbar on all other sites:

![](http://image.prntscr.com/image/1aa0adfd9d784b5aaf67d1cbeb77bb07.png)

Compare this to something like Arqade's topbar:

![](http://image.prntscr.com/image/877a10668f9f47918804a30990733c72.png)

### Expected Behavior

The AskUbuntu topbar should be at the top of the site (replacing the Canonical bar) with the same scroll/transparency as is on other sites.

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-commentReplies","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-linkedPostsInline","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
@KazWolfe I've done this in [dev j](https://github.com/soscripted/sox/raw/dev/sox.user.js), but it's an **optional setting** to enable on ask ubuntu, which you'll need to enable by:

- clicking the `>` arrow next to the fixed topbar setting in the dialog, 
- checking the checkbox, and 
- clicking the save button **underneath the checkbox** (not the main big one!)

---

It's optional because it gets rid of the extra topbar at the very top, which some people might want. and also because the page will always jump around a bit when you load it now, because the script removes the original topbar, meaning everything moves up. So I made it optional because some people couldn't stand that :P I hope you can though! :)
