### ISSUE TITLE
No quickAuthorInfo when reviewing

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#202]
### Current Behaviour

There is currently no quickAuthorInfo when reviewing or when looking at an already-reviewed item. Could this be added?

![image](https://cloud.githubusercontent.com/assets/1776164/21578353/ae32778c-cf31-11e6-9ffe-40d97aab7931.png)

---

### SOX Errors logged to the browser console -- F12 (if available)

(unknown) soup injecting fixes
VM763:30 soup init complete
VM763:30 soup setup complete
VM769:563 SOX:  undefined
VM769:563 SOX:  Object
VM763:30 soup JS fixes applied
VM769:563 SOX:  DEBUGGING SOX VERSION 2.0.3DEVw
VM769:563 SOX:  ----------------saved variables---------------------
VM769:587 SOX:  logging sox stored values --- 
VM769:587 SOX:  access token set
VM769:587 SOX:  SOX-debug
VM769:587 SOX:  true
VM769:587 SOX:  SOXSETTINGS
VM769:587 SOX:  ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]
VM769:587 SOX:  downvotedPostsEditAlert
VM769:587 SOX:  {}
VM769:587 SOX:  editReasons
VM769:587 SOX:  [["formatting","Improved Formatting"],["spelling","Corrected Spelling"],["grammar","Fixed grammar"],["greetings","Removed thanks/greetings"]]
VM769:587 SOX:  metaNewQuestionAlert-lastQuestions
VM769:587 SOX:  {"meta.tex":"How to including multimedia files in beamer [Work in progress, please ignor for the moment]"}
VM769:563 SOX:  ----------------end saved variables---------------------
VM769:563 SOX:  initializing SOX dialog
VM769:563 SOX:  injecting features into dialog
VM769:563 SOX:  Object
VM769:563 SOX:  running addAuthorNameToInboxNotifications
VM769:563 SOX:  observe: .inbox-dialog
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  running bulletReplace
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  running fixedTopbar
VM769:563 SOX:  observe: #notify-container,#notify--1
VM769:563 SOX:  observe: .review-bar
VM769:563 SOX:  Object
VM769:563 SOX:  running highlightQuestions
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  running markEmployees
VM769:563 SOX:  SOX Access Token: SET
VM769:563 SOX:  Object
VM769:563 SOX:  running scrollToTop
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  running standOutDupeCloseMigrated
VM769:563 SOX:  observe: #user-tab-questions, #question-mini-list
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  running addSBSBtn
VM769:563 SOX:  observe: li[id^="wmd-redo-button"], textarea[id^="wmd-input"]
VM769:563 SOX:  observe: .wmd-preview.sbs-on
VM769:563 SOX:  Object
VM769:563 SOX:  running editComment
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  running enhancedEditor
VM769:563 SOX:  observe: li[id^="wmd-redo-button"], textarea[id^="wmd-input"]
VM769:563 SOX:  Object
VM769:563 SOX:  running kbdAndBullets
VM769:563 SOX:  observe: [id^="wmd-redo-button"], textarea[id^="wmd-input"]
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  running downvotedPostsEditAlert
VM769:563 SOX:  downvotedPostsEditAlert posts to check
VM769:563 SOX:  Object
VM769:563 SOX:  downvotedPostsEditAlert notifications
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  running flagOutcomeTime
VM769:563 SOX:  Object
VM769:563 SOX:  running flagPercentages
VM769:563 SOX:  Object
VM769:563 SOX:  running flagPercentageBar
VM769:563 SOX:  Object
VM769:563 SOX:  running hideHireMe
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  Object
VM769:563 SOX:  running warnNotLoggedIn
https://api.stackexchange.com/2.2/users/?site=tex&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=OVgj6ZlXkJ8KdPW9(j1T0Q)) Failed to load resource: the server responded with a status of 400 (Bad Request)
VM769:563SOX:  fire: target: 
VM769:563SOX:  <div class=​"review-bar" style=​"position:​ static;​ margin-top:​ 0px;​ width:​ 1058px;​">​…​</div>​
VM769:563SOX:  fire: target: 
VM769:563SOX:  <div class=​"review-bar" style=​"position:​ static;​ margin-top:​ 0px;​ width:​ 1058px;​">​…​</div>​
VM769:563SOX:  fire: target: 
VM769:563SOX:  <div class=​"review-bar" style=​"position:​ static;​ margin-top:​ 0px;​ width:​ 1058px;​">​…​</div>​
VM769:563SOX:  fire: target: 
VM769:563SOX:  <div class=​"review-bar" style=​"position:​ static;​ margin-top:​ 0px;​ width:​ 1058px;​">​…​</div>​
DevTools failed to parse SourceMap: http://tex.stackexchange.com/review/close/jquery.timeago.min.js.map

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment]
Thanks for writing up a 'formal' request :)

It's been in my mental to do list for a bit too long now :/

Happy new year btw! :)

On 31 Dec 2016 4:16 p.m., "wgrundlingh" <notifications@github.com> wrote:

Installed Version: 2.0.3DEVw Environment: Tampermonkey Current Behaviour

There is currently no quickAuthorInfo when reviewing. Could this be added?
------------------------------
SOX Errors logged to the browser console -- F12 (if available)
------------------------------
Steps to reproduce
------------------------------
Features Enabled

["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/soscripted/sox/issues/202>, or mute the thread

**Comment by shu8** [comment]
@wgrundlingh done in [dev y](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

cc/ @fixer1234 you were also interested in this feature -- it's done! :)

**Comment by fixer1234** [comment]
@shu8 Nice!
