### ISSUE TITLE
Remove ads on sites with low reputation

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#236]
### Current Behaviour

Feature request: remove ads on certain sites you have low reputation.

I don't have the same reputation on all sites, but contribute quite heavily on some. Perhaps offer users of SOX the option of removing ads altogether.

![image](https://cloud.githubusercontent.com/assets/1776164/22004109/e15df15c-dc0d-11e6-9f62-d53dca809319.png)

Related: [We're enabling display ads on select Stack Exchange sites](http://meta.stackexchange.com/q/287242/168244)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode"]

**Comment by shu8** [comment]
I'm not sure about this one @wgrundlingh, because SOX runs after the page has loaded so you'll probably see a jump in the page once the ad's been removed.

AFAIK, AdBlock is pretty good at not making the page jump when it removes ads, but I'm not sure how it works :/ if you have it installed it's probably worth a try!

Also, the ad you posted in your screenshot seems like the one that gets removed at 200 rep. If you have >200 rep, you might want to check you haven't accidentally enabled them in your site preferences (it was recently made possible to re-enable those ads if you wanted). If you don't have 200 rep, then fair enough :)

@enki-code what do you think?

**Comment by enki-code** [comment]
@shu8 We should be able to do this, no problem. 

I will look into the DOM flickering, basically we would just need to inject the script a little earlier in the process (_I've been meaning to get to this for quite some time_).

**Comment by shu8** [comment]
@wgrundlingh looking back at this again, it doesn't seem like we'll be able to get this done very effectively  in SOX as it is a userscript :/

I would suggest installing AdBlock if you don't already have it because it's really good at making ads disappear quickly, much quicker than a userscript will be able to do!

Sorry about this :(
