### ISSUE TITLE
Add a label on questions which are hot-network questions has stopped working

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#28]
**Installed Version: 1.0.2  |  Environment: Windows/Firefox/GreaseMonkey**

**Expected Behavior**

"Hot question" normally appears somewhere to the top right of the question IIRC.

**Actual Behavior**

"Hot question" not appearing. 

![screenshot - 20_03_2016 11_04_31](https://cloud.githubusercontent.com/assets/7079224/13904076/e0c5b326-ee8b-11e5-84e6-c37acbc2e337.png)

![screenshot - 20_03_2016 11_05_14](https://cloud.githubusercontent.com/assets/7079224/13904077/e6dada34-ee8b-11e5-8451-8787c908f20f.png)

**Error Logs**

![screenshot - 20_03_2016 11_11_27](https://cloud.githubusercontent.com/assets/7079224/13904089/88fdc89e-ee8c-11e5-8c26-bf77596ba567.png)

**Comment by shu8** [comment]
@DavidPostill The feature only works for the latest 30 hot questions because the RSS feed I use on;y gives 30, and it seems the question you're looking at is 32nd right now...

Can you try on a more recent question such as http://codegolf.stackexchange.com/questions/75805/is-this-a-valid-variable-name please?:

<img width="1197" alt="screen shot 2016-03-20 at 12 58 58" src="https://cloud.githubusercontent.com/assets/8850830/13904523/87088a4c-ee9b-11e5-86f3-ce2e10d599bd.png">

This works, and I've tested on FF this time ;)

**Comment by DavidPostill** [comment]
Yes, it works on your example.

**Comment by shu8** [comment]
@DavidPostill great! :D I would make it more than 30 but IFAIK that's impossible because there's no larger RSS feed :( sorry!

**Comment by DavidPostill** [comment]
@shu8 I just checked and now it is showing on my test question. I guess it has moved up the list.

**Comment by shu8** [comment]
@DavidPostill hmmm I see it as well now. That's really weird... I wonder how that works because you'd think the newer questions would stay hot for longer...
