### ISSUE TITLE
Make SO employee icon act like the moderator icon

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#284]
### Installed Version: 2.0.29  Environment: Tampermonkey

Currently, the "Add the SO logo after employee names to make them stand out" option appends an employee icon to the name of the employee. However, unlike the moderator icon, the SO logo can be clicked, has a slightly different color and will be highlighted in the comments of an employee's question:

<img width="674" alt="screen shot 2017-05-17 at 2 55 26 pm" src="https://cloud.githubusercontent.com/assets/5375326/26170863/e5f89fde-3b10-11e7-8a72-87c810f140a3.png">

Since it stands out a bit, could you make it act like the moderator icon? :)

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-hideCertainQuestions","Extras-showMetaReviewCount"]

**Comment by shu8** [comment]
Thanks for these 2 issues :)

We're both extremely busy at the moment with various things, so these might take a few weeks to get done :(

But thanks for raising the issues and we'll get them done ASAP :)

On 17 May 2017 at 19:57, Sir-Cumference <notifications@github.com<mailto:notifications@github.com>> wrote:
Installed Version: 2.0.29 Environment: Tampermonkey

Currently, the "Add the SO logo after employee names to make them stand out" option appends an employee icon to the name of the employee. However, unlike the moderator icon, the SO logo can be clicked, has a slightly different color and will be highlighted in the comments of an employee's question:

[screen shot 2017-05-17 at 2 55 26 pm]<https://cloud.githubusercontent.com/assets/5375326/26170863/e5f89fde-3b10-11e7-8a72-87c810f140a3.png>

Since it stands out a bit, could you make it act like the moderator icon? :)

Features Enabled

["Appearance-addAuthorNameToInboxNotifications","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-hideCertainQuestions","Extras-showMetaReviewCount"]

**Comment by Sir-Cumference** [comment]
@shu8 No problem, take your time. I'll try and work on these to save you the trouble :)

**Comment by shu8** [comment]
@Sir-Cumference finally done! in [dev 2.0.30](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)
