### ISSUE TITLE
Feature suggestion: adding mirror links

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [soscripted/sox#285]
Overtime, many links get broken (e.g., for stack overflow, [10% of the links posted here are dead. How do we deal with them?](https://meta.stackoverflow.com/q/300916/395857)). 

Feature suggestion: have an option to automatically add mirror links to the question/answer/comment being edited.

Example: https://fitness.stackexchange.com/review/suggested-edits/17937

![image](https://cloud.githubusercontent.com/assets/15331/26276916/99cd2152-3d4f-11e7-974a-3e77bc233e1d.png)

There exist APIs for that purpose: [API or library to obtain a mirror of a link](https://softwarerecs.stackexchange.com/q/42188/903)

**Comment by shu8** [comment]
@Franck-Dernoncourt thank for the suggestion, but it seems like a helpful feature to have on all sites, so you might be better off installing extensions like [Dead Link](https://chrome.google.com/webstore/detail/dead-link/cbhijdjkncfjjiodgafikkafnnmicnna) or [Wayback Machine](https://chrome.google.com/webstore/detail/wayback-machine/fpnmgdkabkmnadcjpehmlllkndpkmiak) that will let you easily get archived pages if you ever land on a dead link :)

---

Just because, to implement this on SOX would require checking *every single* link on each page to see if they're dead which would be *a lot* of unnecessary requests over time and I think these extensions (and variations) solve the problem in a better way :)
