### ISSUE TITLE
Button to efficiently flag individual comments as no longer needed

### ISSUE THREAD

**Issue by GaurangTandon** [soscripted/sox#327]
I often go through my previous questions on SO/SE and find a lot of them have long resolved discussions. Ideally, I should raise a post flag and say "all comments below are obsolete; please delete". However, quite often there are 20 comments, out of which - say - only comments 1, 2, 3, 5, 8, and 13 are obsolete. In such a case, I've to manually flag each of them as no longer needed.<sup>\[1\]</sup>

**Feature request:**  ave a separate button next to every comment which when clicked would directly raise a no longer needed flag on it. If the button is pressed a second time in quick succession, the code would accept the press, but wait for for five seconds to pass before sending the flag request to the SE API.

Alternatively, we can have a single button at the top of the comment thread. When clicked, it would enable "batch-flag-mode": where we can select several comments via checkboxes (would require changing the UI a bit). We can then select a single "r&a/nlg/custom" flag on all of them.

If you're busy, I can do this myself, but I was hoping for some pointers from your side (what code to use?), and also if this would be a good fit for SOX. And in case you've a better alternative way, please share! Thanks!

----

Note1: from what I've been able to father from several meta.SE discussions, there isn't clear consensus among the SE mods as to whether they prefer individual flags or a single flag. ([see](https://meta.stackexchange.com/questions/299103/can-we-remove-the-5-second-rate-limiting-on-comment-flags#comment972207_299106)) Thus, a safe bet to achieve the intended effect is to flag individually.

**Comment by shu8** [comment]
@GaurangTandon sounds like a cool idea! I will be busy for the next month or so with exams, so please do feel free to try implementing it if you have time!

I tend to make big features (such as this) as a separate userscript first before integrating them into SOX just because it's easier to test!

You might be interested in looking at my [Self-destructing comments](https://stackapps.com/q/6316) userscript to see how I did something similar but for deletion instead of flagging. I haven't edited this in a long time and I don't know if I commented it much, but you might be able to make something out of it! 😆

**Comment by GaurangTandon** [comment]
Hey, so [it's ready](https://stackapps.com/questions/7935/bulk-flag-comments) and working great. Unfortunately, it's quite large and am afraid it will likely cause feature bloat for SOX :( (https://github.com/GaurangTandon/BulkFlagCommentsSE)

So, I would rather have it as a separate userscript, at least for now,

**Comment by shu8** [comment]
@GaurangTandon that's great! no problem -- some things are just better on their own! :)
