### ISSUE TITLE
Set the same zoom level for all sites

### ISSUE THREAD

**Issue by ooker777** [soscripted/sox#386]
If you want to zoom the site to 120%, you need to manually do it on every site. Even if you have zoomed a site's main site, you have to do this in its meta as well. It would be great if the zoom level is set for all pages.

I think the script would need to provide the number of key press for the zooming level (say 2), and then send <kbd>Ctrl =</kbd> with the equal times.

(Sorry for my English) 

**Suggested descriptions**
Set zoom level the same in every page

**Comment by shu8** [comment]
Thanks for the feature request @ooker777. I think this is a feature that's more generic to any website rather than for Stack Exchange ones and probably isn't a great fit in SOX.

Have you considered installing a separate extension like https://chrome.google.com/webstore/detail/custom-page-zoom/jodiabicmogcbbiocceenmeflipeelle?hl=en for this? 

The advantage of a native extension like that would be it'll work on any other sites you like to zoom in on and would probably be more reliable because it has access to the Chrome API so can zoom properly rather than needing to do something hacky in SOX like modify the CSS zoom or try using the keyboard to do it!

I'm going to close this as I don't think SOX will benefit from this particular feature, I think using a different extension is a better idea for this! :)
