### ISSUE TITLE
Pre-defined edit comment options (checkboxes) option no longer works after the newest updates

### ISSUE THREAD

**Issue by double-beep** [soscripted/sox#395]
**Describe the bug**
The "Pre-defined edit comment options (checkboxes)" option no longer works after the newest updates in the dev branch. I will try to do a bisect at the end of the date, maybe, if I have some time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a random post.
2. Click on 'edit'
3. There doesn't seem to be the canned reasons

**Expected behaviour**
The canned reasons should appear

**Screenshots/GIFs**
![image](https://user-images.githubusercontent.com/38133098/58759291-2c51e600-8530-11e9-9ee2-77bbbdb1b75e.png)

**Environment**
Microsoft Edge 44.17763.1.0, TamperMonkey v4.9.5942

**Comment by shu8** [comment]
Thanks @double-beep, I did make quite a few changes last night and hoped I hadn't broken anything!

Fixed in [dev 2.4.31](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

(the bug was introduced in [this commit](https://github.com/soscripted/sox/commit/caf5165dcddbaa606d759d5f1887ceb7e8495b42#diff-9ebc851cf61f35b265280b710bcffcc8R393) if you're interested)

**Comment by double-beep** [comment]
I see; thank you very much!

**Comment by SmartManoj** [comment]
Again not working

**Comment by SmartManoj** [comment]
Rename `Pre-defined edit comment options` to `Pre-defined options for edit summary`
