### ISSUE TITLE
Copy comments as markdown

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#408]
**Describe the feature you'd like**
Copy button to copy comments in markdown

**Comment by shu8** [comment]
I personally found Brock's script really good for this: [Get Comment markdown, copy comment code to clipboard](https://stackapps.com/questions/8296/).

I'll leave this open because it could be a nice small feature for SOX, and I'd be happy to accept a pull request from anyone, but seeing as a userscript already exists for the feature it won't be extremely high priority!

**Comment by shu8** [comment]
I've added this feature in [dev 2.6.20](https://github.com/soscripted/sox/raw/dev/sox.user.js).
