### ISSUE TITLE
Not worked?

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#479]
**Describe the bug**
For the first time one have to click save changes in settings to make it work

**SOX errors logged in console**
Not captured

**Environment**
SOX version: 2.6.37DEV
Platform: Tampermonkey

**Comment by SmartManoj** [comment]
Which is the root cause for #463

**Comment by shu8** [comment]
Thanks for raising this issue @SmartManoj.

Needing to click "Save Changes" in the settings dialog is **desired behaviour**. SOX won't do anything until the user explicitly confirms what features they want.

The alternative would be for SOX to decide what features to enable on first-install, which goes against what SOX exists for -- everything should be optional.

**Comment by SmartManoj** [comment]
Is this new behavior?
It should tell the user to click save changes. 
But it should ask to choose feature on first-install.

**Comment by shu8** [comment]
You should get an alert on first install prompting you to get an access token, and the dialog should show up when that alert pops up. 

Does that happen for you? If not, please could you follow the issue template and describe steps to reproduce the behaviour, and the exact expected behaviour, to make it easier to debug and track this issue! :)

**Comment by SmartManoj** [comment]
It does. Will the alert tell the user to click save changes?
