### ISSUE TITLE
Favorite Question Tag Highlighting with Wildcards*

### ISSUE THREAD

**Issue by enki-code** [soscripted/sox#48]
**Installed Version: 1.0.4DEV  |  Environment: Tampermonkey/Chrome**

The favorite question tag highlighting should work with tag wildcards `*`.

Right now, it's missing a lot.

![tag-skipping](https://cloud.githubusercontent.com/assets/12533449/14407590/063bd362-fe84-11e5-9656-e9aba534c026.png)

**Comment by shu8** [comment]
@enki-code I see this:

<img width="763" alt="screen shot 2016-04-10 at 10 36 44" src="https://cloud.githubusercontent.com/assets/8850830/14409348/244718d8-ff08-11e5-8917-480640672548.png">

When I have the asp.net-mvc* tag favourited... are you sure you have the latest DEV installed?

If you do, any errors in console? Because it seems to be working for asp.net-mvc, which means the regex is being converted properly...

**Comment by shu8** [comment]
@enki-code does this still happen? Anything in the console?

**Comment by enki-code** [comment]
@shu8 
Yeah, it's still happening, no errors in the console..  I will reinstall and check later, I'm in a rush to get out of the house today. Sorry.

**Comment by shu8** [comment]
@enki-code sure no problem :)

**Comment by enki-code** [comment]
No errors in the console.  

It's still skipping some tags though.

![tag-wildcards](https://cloud.githubusercontent.com/assets/12533449/14589194/d60ba5e2-0490-11e6-88de-bb1d708ee8b4.png)

![tag-wildcards2](https://cloud.githubusercontent.com/assets/12533449/14589211/207dc966-0491-11e6-9db3-7da6c68ebc70.png)

**Comment by shu8** [comment]
@enki-code hmm.. ok thanks. I'll look into it a bit deeper ;|

**Comment by shu8** [comment]
@enki-code dunno if this fixes your problem... but I've tweaked the script a bit. Can you reinstall and check if it's fixed for you? :)

**Comment by enki-code** [comment]
Yay!! It's a dream come true. I love it.
