### ISSUE TITLE
'Get access token?' link broken

### ISSUE THREAD

**Issue by rjrudman** [soscripted/sox#50]
**Installed Version: v1.0.3  |  Environment: Chrome/Tampermonkey Version 49.0.2623.110 m**

**Expected Behavior**

Link should work on all stack exchange sites, or guide the user to `meta.stackexchange.com` to get their access token

**Actual Behavior**

Clicking a link while *not* on http://meta.stackexchange.com/ throws an error.

**Error Logs**

> VM2649:3464 Uncaught channelUrl must be under the current domain  
> r@ VM2649:3464  
> (anonymous function) @ VM2649:3740  
> n.event.dispatch @ VM2649:8  
> r.handle @ VM2649:8

**Steps to reproduce**

Visit http://stackoverflow.com/
Open up the settings
Click on 'Get access token?'

**Comment by shu8** [comment]
@rjrudman thanks for posting here! I think I have a fix ready, just testing and then I'll push :)

**Comment by shu8** [comment]
@rjrudman ok, it's fixed :)

Please could you install [1.0.4 DEV](https://github.com/soscripted/sox/blob/dev/sox.user.js) and confirm this is now working for you?

---

if you're interested...: :)

When registering an app on Stack Apps, you have to give an Oauth Domain, which has to be a single site, so I've made it check for which site you're on and compare it to the current site. If you're not on the given Oauth Domain site, it alert's you that you need to be, otherwise it works as normal :)

Thanks again for the bug report!

**Comment by rjrudman** [comment]
Yep - works perfectly, thanks! :)
